### ISSUE TITLE
Does not capture errors from reading config file

### ISSUE THREAD

**Issue by Zylphrex** [getsentry/sentry-airflow#5]
In GCP composer, adding

```
[core]
...
dags_are_paused_at_creation = True
```

seems to cause the following error

```
Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 7, in <module> exec(compile(f.read(), __file__, 'exec'))
  File "/usr/local/lib/airflow/airflow/bin/airflow", line 21, in <module> from airflow import configuration
  File "/usr/local/lib/airflow/airflow/__init__.py", line 36, in <module> from airflow import settings, configuration as conf
  File "/usr/local/lib/airflow/airflow/settings.py", line 268, in <module> configure_orm()
  File "/usr/local/lib/airflow/airflow/settings.py", line 171, in configure_orm pool_recycle = conf.getint('core', 'SQL_ALCHEMY_POOL_RECYCLE')
  File "/usr/local/lib/airflow/airflow/configuration.py", line 276, in getint return int(self.get(section, key))
ValueError: invalid literal for int() with base 10: '1800\ndags_are_paused_at_creation = True'
```

that is not being captured by the plugin and reported to Sentry

**Comment by tiopi** [comment]
With the current plugin method, Sentry is run when plugins are imported. I believe that airflow first configures the conf file before importing any plugins. There is a PR against Airflow that will fix this issue https://github.com/apache/airflow/pull/5407.
